---
title: Humanitarian OpenStreetMap Team
timezone: UTC
collections:
  where-we-work:
    title: Countries
    output: true
  impact-areas:
    title: Impact Areas
    output: true
  jobs:
    title: Jobs
    output: true
  posts:
    title: News Posts
    output: true
  partners:
    title: Partners
    output: true
  people:
    title: People
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  tools:
    title: Tools
    output: true
  uploads:
    title: Uploads
    output: true
  working-groups:
    title: Working Groups
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: updates/:title/
    layout: news-item
    Summary Text: 
    Feature Image: 
    Person: 
    Working Group:
    - ''
    Country:
    - ''
- scope:
    path: ''
    type: people
  values:
    layout: person
    Photo: 
    Member Type:
      Is Staff: 
      Is Voting Member: 
      Is Board Member: 
    Title: 
    Working Group:
    - ''
    Project:
    - ''
    Country: 
    Social Media (Full URL):
      OSM: 
      Twitter: 
      LinkedIn: 
      Facebook: 
      Instagram: 
- scope:
    path: ''
    type: impact-areas
  values:
    layout: impact-area
- scope:
    path: ''
    type: tools
  values:
    layout: impact-area
    Tool URL: 
- scope:
    path: ''
    type: jobs
  values:
    layout: page
    Deadline Date: 
    Place of Work: 
- scope:
    path: ''
    type: where-we-work
  values:
    layout: country
    Contact Person:
      Name: 
      Title: 
      Email: 
      Phone: 
    Location:
      Location Name: 
      Address: 
      Phone: 
      Map Link: 
- scope:
    path: ''
    type: projects
  values:
    layout: project-item
    Project Summary Text: 
    Feature Image: 
    HOT Involvement: 
    Country:
    - ''
    Impact Area:
    - ''
    Person:
    - ''
    Partner:
    - ''
    Duration:
      Start Date: 
      End Date: Ongoing
email: info@hotosm.org
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: 
url: 
twitter_username: hotosm
github_username: hotosm
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-paginate
paginate: 16
paginate_path: "/updates/page:num/"
